lessonplan:
  qr-code-size: 150
  video-file-qr-code-extractor:
    grab-step-frames: ${grab.step.frames:24}
    degree-of-parallelism: 2
    ignore-qrcode-text-with-numbers-only: true

logging:
  level:
    ru.otus.lessonplan: info
  file.name: logs/logfile.txt
